name: Release

on:
  push:
    branches:
      - main
env:
  kubeadm_version: v1.25.3
  kubekey_version: v3.0.7

jobs:
  build:
    name: create draft release
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run:  echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - name: git clone
        run: |
          git clone --depth 1 --branch ${kubekey_version} https://github.com/kubesphere/kubekey.git
          cd kubekey
          wget https://github.com/lework/kubeadm-certs/releases/download/${kubeadm_version}/kubeadm-linux-amd64
          tmp=$(mktemp)
          kubeadm_sha256sum=$(sha256sum kubeadm-linux-amd64 | cut -d " " -f 1)
          components_file_path="kubekey/version/components.json"
          jq --arg a "$kubeadm_sha256sum" '.kubeadm.amd64."${kubeadm_version}" = $a' ${components_file_path} > "$tmp" && mv "$tmp" ${components_file_path}

      - name: generate release artifacts
        run: |
          export RELEASE_TAG=${kubekey_version}
          make release
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: out/*
