name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: create draft release
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run:  echo "RELEASE_TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - name: git clone
        run: |
          git clone https://github.com/kubesphere/kubekey.git --depth=1 -b v3.0.7
      - name: generate release artifacts
        run: |
          cd kubekey
          ls
          make release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: out/*
